name: appwrite_auth_ui
description: UI library to implement auth forms using Appwrite and Flutter
version: 0.0.2
homepage: https://appwrite.io/
repository: https://github.com/jtmuller5/appwrite_auth_ui
# flutter pub publish --dry-run

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: 9.0.1
  email_validator: ^2.0.1
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logos/google_light.png

screenshots:
  - description: "Appwrite Auth UI"
    path: assets/appwrite_auth.png